services:
  coreshop.core.members.index.helper:
    class: CoreShop\Bundle\CoreBundle\Index\RestrictionIndexHelper
    arguments:
      - '@members.configuration'
      - '@members.manager.restriction'
    tags:
      - { name: coreshop.index.class_helper }