members:
  user:
    adapter:
      class_name: '%coreshop.model.customer.pimcore_class_name%'
  group:
    adapter:
      class_name: '%coreshop.model.customer_group.pimcore_class_name%'

  restriction:
    enabled: true
    allowed_objects: ['%coreshop.model.product.pimcore_class_name%', '%coreshop.model.category.pimcore_class_name%']


core_shop_customer:
  pimcore:
    customer_group:
      classes:
        install_file: '@CoreShopMembersBridgeBundle/Resources/install/pimcore/classes/CoreShopCustomerGroup.json'
    customer:
      classes:
        install_file: '@CoreShopMembersBridgeBundle/Resources/install/pimcore/classes/CoreShopCustomer.json'

core_shop_product:
  pimcore:
    product:
      classes:
        repository: CoreShop\Bundle\CoreShopMembersBridgeExtension\Pimcore\Repository\ProductRepository
    category:
      classes:
        repository: CoreShop\Bundle\CoreShopMembersBridgeExtension\Pimcore\Repository\CategoryRepository
